import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div>
      <Head>
        <title> Michelle Elek </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    {/* // USE REF TO a=ADD SCROLL FUNCTION FOR ONE BIG PAGE */}

      <main>
        <div>
          <h1> Michelle Elek </h1>
          <p> Michelle is a full-stack software engineer with a fondness of backend frameworks. </p>
        </div>
      </main>

      <footer>
      </footer>
    </div>
  )
}
